  let shoes=[
            {
                id:1,
                image:"bewkoof_img/1s,1.webp",
                price:100
            },
            {
                id:2,
                image:"bewkoof_img/1s,3.webp",
                price:200
            },
            {
                id:3,
                image:"bewkoof_img/2s,1.webp",
                price:300
            },
            {
                id:4,
                image:"bewkoof_img/2s,2.webp",
                price:400
            },
            {
                id:5,
                image:"bewkoof_img/2s,3.webp",
                price:500
            },
            {
                id:6,
                image:"bewkoof_img/2s,4.webp",
                price:600
            },
            {
                id:7,
                image:"bewkoof_img/2s,5.webp",
                price:700
            },
            {
                id:8,
                image:"bewkoof_img/3s,1.webp",
                price:800
            },
            {
                id:9,
                image:"bewkoof_img/3s,2.webp",
                price:900
            },
            {
                id:10,
                image:"bewkoof_img/3s,3.webp",
                price:1000 
            }
        ]

        export default shoes;